uploads = []
generated = []

[[outputs]]
id = "ziGmvtdleyYiarqTeN-VS"
uri = "file://StreamNova/app/build/outputs/apk/debug/ultragol_v2.0.zip"
type = "unspecified"
title = "Ultragol v2.0 — APK (debug)"

[[outputs]]
id = "IXQQk40o4Jm5erqk9jSwt"
uri = "file://StreamNova/app/build/outputs/apk/debug/ultragol_v2.0_fixed.zip"
type = "unspecified"
title = "Ultragol v2.0 — APK corregida (con nuevo ícono)"

[[outputs]]
id = "iGsQj8qFix8Ia2Rr8HX4Q"
uri = "file://StreamNova/app/build/outputs/apk/debug/ultragol_v3.0_features.zip"
type = "unspecified"
title = "Ultragol v3.0 — APK con todas las nuevas funciones"

[[outputs]]
id = "pGdv3u5k_1wvAYK12j31T"
uri = "file://apks/ultragol.zip"
type = "unspecified"
title = "Ultragol APK actualizado"
